<?php
/**
 * AIPRO Contracts — installer.
 *
 * Re-runnable: it can be executed repeatedly. Existing config is detected and
 * prefilled; migrations only apply what's pending; the admin account is upserted;
 * seed data is inserted only when missing. An optional "fresh install" wipes the
 * schema so everything is rebuilt from scratch.
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

require __DIR__ . '/app/helpers.php';

use App\Core\Config;
use App\Core\Database;
use App\Core\Migrator;
use App\Models\Package;
use App\Models\User;

const CONFIG_PATH = __DIR__ . '/config/config.php';

$alreadyInstalled = is_file(CONFIG_PATH);
$existing = $alreadyInstalled ? (require CONFIG_PATH) : null;
$baseUrl = rtrim(str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'])), '/');

$errors = [];
$done = false;

/** Write config/config.php from the collected values. */
function write_config(array $db, array $app, string $appKey): bool
{
    $data = [
        'app' => [
            'name'                 => $app['name'],
            'env'                  => 'production',
            'debug'                => false,
            'timezone'             => $app['timezone'],
            'unit_days'            => (int) $app['unit_days'],
            'contract_months'      => 12,
            'max_extension_months' => 6,
        ],
        'db'      => $db,
        'app_key' => $appKey,
    ];
    $php = "<?php\n// Generated by install.php on " . date('c') . ". Do not commit.\nreturn "
         . var_export($data, true) . ";\n";
    if (!is_dir(dirname(CONFIG_PATH))) {
        @mkdir(dirname(CONFIG_PATH), 0775, true);
    }
    return (bool) file_put_contents(CONFIG_PATH, $php);
}

/** Drop every app table (FK-safe) for a fresh install. */
function drop_all(\PDO $pdo): void
{
    $pdo->exec('SET FOREIGN_KEY_CHECKS=0');
    foreach (['extension_requests','redemptions','unit_ledger','contracts','packages','users','settings','migrations'] as $t) {
        $pdo->exec("DROP TABLE IF EXISTS `{$t}`");
    }
    $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
}

/** Seed the default sellable packages (idempotent by code). */
function seed_packages(int $unitDays): void
{
    $defaults = [
        ['starter', 'Starter', 'ลูกค้าบุคคล / ทีมเล็ก', 12, 750, 690, null, 'active', 1],
        ['team', 'Team', 'ทีม 5–20 คน', 60, 750, 630, 'ยอดนิยม', 'promo', 2],
        ['scale', 'Scale', 'องค์กรขนาดกลาง', 240, 750, 550, '-20%', 'active', 3],
        ['midyear', 'Mid-Year Boost', 'ส่วนลดเฉพาะช่วง · จำกัด 200 สัญญา', 60, 630, 499, 'โปรฯ', 'promo', 4],
    ];
    foreach ($defaults as [$code, $name, $note, $units, $list, $sale, $promo, $status, $sort]) {
        if (Package::findByCode($code)) {
            continue;
        }
        Package::insert([
            'code' => $code, 'name' => $name, 'note' => $note, 'units' => $units,
            'unit_days' => $unitDays, 'list_price' => $list, 'sale_price' => $sale,
            'promo_label' => $promo, 'status' => $status, 'sort_order' => $sort,
        ]);
    }
}

/** Optional demo data so the admin dashboard isn't empty. */
function seed_demo(int $unitDays): void
{
    if (User::findByEmail('demo@sinnovate.co')) {
        return; // already seeded
    }
    $svc = new App\Services\ContractService();
    $uid = User::create('demo@sinnovate.co', 'demo1234', 'บริษัท ซินโนเวท จำกัด (เดโม)', 'customer');
    $scale = Package::findByCode('scale');
    $cid = $svc->purchase($uid, 'บริษัท ซินโนเวท จำกัด (เดโม)', 240, (int) ($scale['sale_price'] ?? 550), (int) ($scale['id'] ?? null));
    // A successful redemption (bound seat) and a pending one.
    $r1 = $svc->redeem($cid, 'ops@sinnovate.co', 12);
    $svc->setRedemptionStatus($r1, 'success');
    $svc->redeem($cid, 'data@sinnovate.co', 6);
    // A pending extension request.
    $svc->requestExtension($cid, 2, 'ขยายทีมช้ากว่าแผน ขอใช้โควตาที่เหลือ');
}

// --- Handle submission --------------------------------------------------------
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db = [
        'host'    => trim($_POST['db_host'] ?? '127.0.0.1'),
        'port'    => (int) ($_POST['db_port'] ?? 3306),
        'name'    => trim($_POST['db_name'] ?? 'aifin'),
        'user'    => trim($_POST['db_user'] ?? 'root'),
        'pass'    => (string) ($_POST['db_pass'] ?? ''),
        'charset' => 'utf8mb4',
    ];
    $app = [
        'name'      => trim($_POST['app_name'] ?? 'AIPRO Contracts') ?: 'AIPRO Contracts',
        'timezone'  => trim($_POST['timezone'] ?? 'Asia/Bangkok') ?: 'Asia/Bangkok',
        'unit_days' => max(1, (int) ($_POST['unit_days'] ?? 30)),
    ];
    $adminName  = trim($_POST['admin_name'] ?? '');
    $adminEmail = trim($_POST['admin_email'] ?? '');
    $adminPass  = (string) ($_POST['admin_pass'] ?? '');
    $fresh      = !empty($_POST['fresh']);
    $withDemo   = !empty($_POST['demo']);

    // Validate.
    if ($adminName === '') {
        $errors[] = 'กรุณากรอกชื่อผู้ดูแลระบบ';
    }
    if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) {
        $errors[] = 'อีเมลผู้ดูแลระบบไม่ถูกต้อง';
    }
    if (strlen($adminPass) < 8) {
        $errors[] = 'รหัสผ่านผู้ดูแลระบบต้องมีอย่างน้อย 8 ตัวอักษร';
    }

    // Test connection (server only) and create database.
    if (!$errors) {
        $err = Database::testConnection($db, false);
        if ($err !== null) {
            $errors[] = 'เชื่อมต่อฐานข้อมูลไม่สำเร็จ: ' . $err;
        }
    }

    if (!$errors) {
        try {
            $server = Database::connect($db, false);
            $server->exec("CREATE DATABASE IF NOT EXISTS `{$db['name']}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

            // Persist config, then boot the app connection from it.
            $appKey = ($existing['app_key'] ?? '') ?: bin2hex(random_bytes(32));
            if (!write_config($db, $app, $appKey)) {
                throw new RuntimeException('เขียนไฟล์ config/config.php ไม่ได้ — ตรวจสอบสิทธิ์การเขียนโฟลเดอร์ config/');
            }
            Config::load(CONFIG_PATH);
            date_default_timezone_set($app['timezone']);
            $pdo = Database::instance();

            if ($fresh) {
                drop_all($pdo);
            }

            // Schema + seed.
            (new Migrator($pdo))->migrate();
            seed_packages((int) $app['unit_days']);
            User::upsertAdmin($adminEmail, $adminPass, $adminName);
            if ($withDemo) {
                seed_demo((int) $app['unit_days']);
            }

            $done = true;
        } catch (\Throwable $e) {
            $errors[] = 'ติดตั้งไม่สำเร็จ: ' . $e->getMessage();
        }
    }
}

// Prefill values.
$v = [
    'db_host'    => $existing['db']['host'] ?? '127.0.0.1',
    'db_port'    => $existing['db']['port'] ?? 3306,
    'db_name'    => $existing['db']['name'] ?? 'aifin',
    'db_user'    => $existing['db']['user'] ?? 'root',
    'db_pass'    => $existing['db']['pass'] ?? '',
    'app_name'   => $existing['app']['name'] ?? 'AIPRO Contracts',
    'timezone'   => $existing['app']['timezone'] ?? 'Asia/Bangkok',
    'unit_days'  => $existing['app']['unit_days'] ?? 30,
];
$p = fn(string $k) => htmlspecialchars((string) ($_POST[$k] ?? $v[$k] ?? ''), ENT_QUOTES, 'UTF-8');
?>
<!doctype html>
<html lang="th">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ติดตั้ง · AIPRO Contracts</title>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Thai:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/css/app.css">
</head>
<body>
<div style="max-width:720px;margin:0 auto;padding:40px 20px 80px">
  <div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
    <span class="logo" style="width:34px;height:34px"></span>
    <div><h1 style="margin:0;font-size:24px">ติดตั้ง AIPRO Contracts</h1>
    <div class="muted" style="font-size:13.5px">PHP <?= PHP_VERSION ?> · ตัวติดตั้งนี้รันซ้ำได้อย่างปลอดภัย</div></div>
  </div>

  <?php if ($alreadyInstalled && !$done): ?>
    <div class="flash flash-info" style="margin-top:18px">ระบบถูกติดตั้งไว้แล้ว — คุณสามารถรันซ้ำเพื่ออัปเดตค่า/รัน migration หรือรีเซ็ตข้อมูลใหม่ทั้งหมดได้</div>
  <?php endif; ?>

  <?php foreach ($errors as $err): ?>
    <div class="flash flash-danger" style="margin-top:12px"><?= htmlspecialchars($err) ?></div>
  <?php endforeach; ?>

  <?php if ($done): ?>
    <div class="card card-pad" style="margin-top:20px">
      <div class="flash flash-success" style="margin:0 0 16px">ติดตั้งสำเร็จ 🎉</div>
      <p class="muted" style="margin:0 0 16px;line-height:1.7">
        ฐานข้อมูลพร้อมใช้งาน สร้างตารางและข้อมูลเริ่มต้นเรียบร้อยแล้ว<br>
        เข้าสู่ระบบผู้ดูแลด้วยอีเมลและรหัสผ่านที่คุณตั้งไว้
      </p>
      <div style="display:flex;gap:10px;flex-wrap:wrap">
        <a class="btn btn-primary" href="<?= htmlspecialchars($baseUrl) ?>/index.php/login">ไปหน้าเข้าสู่ระบบ</a>
        <a class="btn btn-light" href="<?= htmlspecialchars($baseUrl) ?>/index.php">ไปหน้าแรก (Landing)</a>
      </div>
      <p class="faint" style="margin:18px 0 0;font-size:12.5px">เพื่อความปลอดภัย ควรลบหรือจำกัดสิทธิ์ไฟล์ <code>install.php</code> หลังใช้งานเสร็จ</p>
    </div>
  <?php else: ?>
    <form method="post" class="card card-pad" style="margin-top:20px">
      <h3 style="margin:0 0 12px;font-size:16px">1. ฐานข้อมูล MariaDB</h3>
      <div style="display:flex;gap:12px">
        <div class="field" style="flex:2"><label>โฮสต์</label><input class="input" name="db_host" value="<?= $p('db_host') ?>" required></div>
        <div class="field" style="flex:1"><label>พอร์ต</label><input class="input" name="db_port" value="<?= $p('db_port') ?>" required></div>
      </div>
      <div class="field"><label>ชื่อฐานข้อมูล (จะสร้างให้ถ้ายังไม่มี)</label><input class="input" name="db_name" value="<?= $p('db_name') ?>" required></div>
      <div style="display:flex;gap:12px">
        <div class="field" style="flex:1"><label>ผู้ใช้</label><input class="input" name="db_user" value="<?= $p('db_user') ?>" required></div>
        <div class="field" style="flex:1"><label>รหัสผ่าน</label><input class="input" type="password" name="db_pass" value="<?= $p('db_pass') ?>"></div>
      </div>

      <h3 style="margin:20px 0 12px;font-size:16px">2. ตั้งค่าแอป</h3>
      <div style="display:flex;gap:12px">
        <div class="field" style="flex:2"><label>ชื่อระบบ</label><input class="input" name="app_name" value="<?= $p('app_name') ?>"></div>
        <div class="field" style="flex:1"><label>Timezone</label><input class="input" name="timezone" value="<?= $p('timezone') ?>"></div>
        <div class="field" style="flex:1"><label>วัน/หน่วย (M)</label><input class="input" type="number" name="unit_days" min="1" value="<?= $p('unit_days') ?>"></div>
      </div>

      <h3 style="margin:20px 0 12px;font-size:16px">3. บัญชีผู้ดูแลระบบ</h3>
      <div class="field"><label>ชื่อผู้ดูแล</label><input class="input" name="admin_name" value="<?= htmlspecialchars($_POST['admin_name'] ?? '') ?>" required></div>
      <div style="display:flex;gap:12px">
        <div class="field" style="flex:1"><label>อีเมล</label><input class="input" type="email" name="admin_email" value="<?= htmlspecialchars($_POST['admin_email'] ?? '') ?>" required></div>
        <div class="field" style="flex:1"><label>รหัสผ่าน (≥ 8 ตัวอักษร)</label><input class="input" type="password" name="admin_pass" required></div>
      </div>

      <h3 style="margin:20px 0 12px;font-size:16px">4. ตัวเลือก</h3>
      <label style="display:flex;gap:10px;align-items:flex-start;font-size:13.5px;margin-bottom:10px">
        <input type="checkbox" name="demo" value="1" checked style="margin-top:3px">
        <span>ติดตั้งข้อมูลตัวอย่าง (บัญชีลูกค้าเดโม + สัญญา + คำขอ) เพื่อให้เห็นระบบทำงานทันที</span>
      </label>
      <label style="display:flex;gap:10px;align-items:flex-start;font-size:13.5px;color:var(--danger)">
        <input type="checkbox" name="fresh" value="1" style="margin-top:3px">
        <span><b>ติดตั้งใหม่ทั้งหมด (ลบข้อมูลเดิม)</b> — ลบทุกตารางแล้วสร้างใหม่ ใช้เมื่อต้องการรีเซ็ตระบบ</span>
      </label>

      <button class="btn btn-primary btn-block" type="submit" style="margin-top:22px">เริ่มติดตั้ง</button>
    </form>
  <?php endif; ?>
</div>
</body>
</html>
