<?php
/**
 * Sample configuration.
 *
 * Do NOT edit this file for a live install — run install.php, which generates
 * config/config.php from these keys. This sample is committed for reference.
 */

return [
    'app' => [
        'name'     => 'AIPRO Contracts',
        'env'      => 'production',   // 'production' | 'development'
        'debug'    => false,
        'timezone' => 'Asia/Bangkok',
        // Fixed business rule: 1 unit (M) = this many days of AI Pro access.
        'unit_days'      => 30,
        // Standard contract length (months) and max extension (months).
        'contract_months'   => 12,
        'max_extension_months' => 6,
        // Max units a customer can redeem in a single request.
        'max_redeem_units'  => 12,
    ],
    'db' => [
        'host'    => '127.0.0.1',
        'port'    => 3306,
        'name'    => 'aifin',
        'user'    => 'root',
        'pass'    => '',
        'charset' => 'utf8mb4',
    ],
    // 32+ random bytes, generated by the installer. Used for CSRF / signing.
    'app_key' => '',
];
